### PR TITLE
StringWrapper: impl and tests for Eq, PartialEq, Ord, PartialOrd

### PR DESCRIPTION
**Pull request by radix**
This is for #7. Please let me know if I've done something wrong -- the main tricky thing was ensuring that only the bytes up-to len were compared, ignoring any "uninitialized" bytes in the extra space.

### CODE REVIEW

**Comment by radix** [comment]
I've added Hash as well.

**Comment by SimonSapin** [comment]
Hi. I’m not really interested in maintaining this crate. If you are, I can make you owner of https://crates.io/crates/string-wrapper and you could copy the code into another repository.

**Comment by radix** [comment]
@SimonSapin Sure, I'm willing to maintain it, since I'm using it anyway. Is there anything you need to know from me other than my github username?

**Comment by SimonSapin** [comment]
No, only confirmation that you want it :) I’ve added you now.

**Comment by radix** [comment]
Thank you, @SimonSapin, I'll try to make a new release soon. For future reference, the new location is at https://github.com/radix/string-wrapper.

**Pull request closed without merging**
